language: node_js
node_js:
  - "7"
# Travis-CI Caching
cache:
  directories:
    - node_modules
    
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build